# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeometryBuilderForNIA
                                 A QGIS plugin
 This plugin extracts geometry from database and builds objects for NIA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-14
        copyright            : (C) 2020 by Samiul Choudhury@Patching Associates Acoustical Engieering Ltd.
        email                : schoudhury@patchingassociates.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeometryBuilderForNIA class from file GeometryBuilderForNIA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geometry_builder_for_nia import GeometryBuilderForNIA
    return GeometryBuilderForNIA(iface)
